### ISSUE TITLE
Calling setReadOnly(false) makes color picker input field read-only

### ISSUE THREAD

**Issue by akos-fekete** [TatuLund/ColorPicker#1]
Calling setReadOnly(false) on a ColorPicker instance results in this state:

![kép](https://user-images.githubusercontent.com/43749020/191479593-4e666006-127a-42bc-b0fd-951efa194ccd.png)

This seems to be caused by css rules that check only for the existence of the attribute, like this one: 
```
        :host([readonly]) #colorpicker {
            background: transparent; 
            border: 1px dashed var(--lumo-contrast-30pct);
            pointer-events: none;
        }
```

**Comment by TatuLund** [comment]
Fixed in version 1.1.3.
