### ISSUE TITLE
ColorPicker is broken with vaadin 24.0-SNAPSHOT

### ISSUE THREAD

**Issue by arikanorh** [TatuLund/ColorPicker#2]
It just gives error

![image](https://user-images.githubusercontent.com/17791032/209450306-363fef4c-6e2b-49c6-9d21-4c6806b8d429.png)

**Comment by TatuLund** [comment]
I expect that most of the add-ons need some tuning to make them compatible with Vaadin 24. I just recently made a round most of my newer add-ons to ensure they work with Vaadin 23.3. I would be surprised that if the thing you highlight here is the only thing requiring fixing in ColorPicker. I will start checking Vaadin 24 compatibility of my addons when Vaadin 24 reaches release beta releases / release candidate state. Currently it is a moving target.

**Comment by TatuLund** [comment]
Should be fixed in version 1.3.2

**Comment by TatuLund** [comment]
Actually there was still a small issue in 1.3.2, now fixed in 1.3.3
