### ISSUE TITLE
When changing values with a preset, the state does not change.

### ISSUE THREAD

**Issue by joseph-ybh** [TatuLund/ColorPicker#3]
Changing the color with the colorpicker changes the state.

However, if I use a preset to change the color, the state does not change.

![image](https://user-images.githubusercontent.com/99656436/236672448-e106a1ff-9853-40ae-b1e7-6ffd4626fe0d.png)
![image](https://user-images.githubusercontent.com/99656436/236672466-aa9f2cdf-dde2-4825-8a7b-06ea02d1c7c1.png)

version
```
        <dependency>
            <groupId>org.vaadin.addons.tatu</groupId>
            <artifactId>colorpicker</artifactId>
            <version>1.3.3</version>
        </dependency>
```

**Comment by TatuLund** [comment]
As you see, the color element changed from yellow to brown upon you entry, so state changed. The text field is automatically emptied, that is an intended behavior in the component.

**Comment by TatuLund** [comment]
In version 1.4.0 there is API to disable clearing of the text field.
