### ISSUE TITLE
Set a default value

### ISSUE THREAD

**Issue by eberleant** [TatuLund/ColorPicker#4]
When an invalid string is entered, the color picker becomes invalid and its value becomes null. Is there a way to make the color picker default to a particular color when invalid input is entered, so that the color picker should never actually be in an invalid state?

I tried something like:

```java
colorPicker.addValueChangeListener(event -> {
  if (event.getValue() == null) {
    colorPicker.setValue(defaultColor);
  }
  colorPicker.setInvalid(false);
});
```

but this didn't have the desired effect. The color picker did switch to the default color, but it also remained invalid.

I also tried:

```java
binder.forField(colorPicker)
  .withConverter(pres -> pres == null ? defaultColor : pres, model -> model == null ? defaultColor : model)
  .bind(...)
```

but this didn't work either - the color picker still appeared invalid, and the color swatch on the left was black instead of the default color.

Thanks for your help, and thanks for creating this component! It's really handy.

**Comment by eberleant** [comment]
With DatePicker, there is an `addInvalidChangeListener` method that you can use to set the value of the DatePicker to some arbitrary value (which also clears the invalid state). Maybe a similar method could be added to ColorPicker?

**Comment by TatuLund** [comment]
Thanks for reporting this. 

I found based on your description that there is a bug there. Programmatic setting of the value does not reset invalid state, and it should. I am fixing that as quick remedy. 

Then the other question is a new feature and API. I will wait for Vaadin 24.2 release before going for that. As Vaadin 24.2 will add global API to control whether client side validation should be enforced or not.

**Comment by eberleant** [comment]
Thanks for looking into this! Sounds great.

**Comment by eberleant** [comment]
BTW, I tried to upgrade to version 1.3.4 but ran into this error:

`class file for com.vaadin.flow.component.dialog.GeneratedVaadinDialog not found`

Our project is using Vaadin 24.1.2.

**Comment by TatuLund** [comment]
Oops, it was silly mistake in packaging, I rereleased it as version 1.3.5 now.

**Comment by eberleant** [comment]
Awesome, it works! Thanks again for fixing this so quickly.
