### ISSUE TITLE
ColorPicker does not load/is visible on Vaadin 24.1.7

### ISSUE THREAD

**Issue by asanderson7** [TatuLund/ColorPicker#7]
I have been trying tt get this to work with Vaadin 24.1.7

I have implemented it as per the code displayed in the Vaadin directory for the add-on.

Once the page is up and running and I inspect where the color picker should be all I see is <color-picker></color-picker> (As per the screenshot)

![NoColorPicker](https://github.com/TatuLund/ColorPicker/assets/120374930/bd68c213-9b70-497b-9592-5e8048487477)

I have included the correct version as per the POM file

![POM](https://github.com/TatuLund/ColorPicker/assets/120374930/d04f5e3c-44fa-4a98-a808-713ad9daa3cb)

I have tried to do a full clean of the build and re-implement but I still run into this issue.

Are you able to test against this version and see if it works ? Or see what could be causing this issue ?

**Comment by TatuLund** [comment]
That is strange, the live demo application is Vaadin 24.2.2 and has ColorPicker 1.4.0

https://v-herd.eu/tatulund-addons/colorpickerview

**Comment by asanderson7** [comment]
It does appear to be fine, something somewhere in my code must have been causing a conflict of some sort, but I cannot say what this was, I went to do some other work and when this page loaded, here was a color picker. I am confused, but I have a working color picker
